### ISSUE TITLE
Building shape

### ISSUE THREAD

**Issue by wasp-lahis** [usnistgov/NetSimulyzer-ns3-module#25]
Hi, congrats for this tool!! I have a doubt about the buildings. I read the paper that describe this tool and I observed that the buildings are always in box/rectangle or circle format. Is it possible draw different kinds of building shapes other than those? Like polygons more complex?

**Comment by bpe2** [comment]
Unfortunately, buildings are limited to rectangles based on the [ns-3 Building class](https://www.nsnam.org/docs/models/html/buildings-design.html#the-building-class), which assumes all buildings are rectangles.

As far as more complex polygons for buildings go, I guess that depends on what you mean by that. Often when more complex structures are modeled in ns-3, several buildings are placed together (e.g., imagine an "L" shaped building made up of two touching ns-3 buildings). You'd still be limited to rectangular pieces, though.

If you mean using differently shaped buildings in general, like using an octagon to represent only one ns-3 building, then I could look into some sort of mechanism to display a building given a list of points. However, this might end up being a lot of investment for something only for looks. If there is some sort of model for ns-3 that respects arbitrary building shapes, this might be worth doing then.

Let me know if I caught your question with that.

**Comment by wasp-lahis** [comment]
Yes, you understood. Tks for reply!
