### ISSUE TITLE
Add Options for Non-Uniform Scaling

### ISSUE THREAD

**Issue by bpe2** [usnistgov/NetSimulyzer-ns3-module#28]
Currently, the `NodeConfiguration` and `Decoration` properties of `Height` and `Scale` can only scale the 3D model evenly on each axis (or a 'uniform' scale). Add an additional `Vector3D` property `ScaleAxes`, to allow for setting a scale multiplier for each axis independently.

Also, expand the ns-3 unit target scaling by adding a flag to allow users to use the `Height` (z-axis) property, along with new `Width` (x-axis) and `Depth` (y-axis) properties to scale in ns-3 units only on the corresponding axis.

# Changes
### `ScaleAxes`
`Vector3D` value with the scale to apply to each axis in the order `[x, y, z]`.
Works in conjunction with the existing `Scale` property, which does uniform scaling. 
Does not interact with `KeepRatio`

Default value: `[1.0, 1.0, 1.0]`

### `KeepRatio`
`BooleanValue` value indicating wether or not `Height`, `Width`, & `Depth` should perform a uniform scale or not. (Default: `true`)
* `true`:  `Height`, `Width`, and `Depth` will maintain the aspect ratio of the model. Potentially scaling more than one direction.
* `false`: `Height`, `Width`, and `Depth` scale only their respective axes.

### `Width`
`OptionalValue<double>` value specified in ns-3 units indicating how wide (X-axis) a displayed model should be.

If `KeepRatio` is `true`, then this performs a uniform scale sun that the model's width ends up being the value of this property. 

If `KeepRatio` is `false`, then `Width` will scale the model on the X-axis only

### `Depth`
`OptionalValue<double>` value specified in ns-3 units indicating how deep (Y-axis) a displayed model should be.

If `KeepRatio` is `true`, then this performs a uniform scale sun that the model's depth ends up being the value of this property. 

If `KeepRatio` is `false`, then `Depth` will scale the model on the Y-axis only.

### `Height`
If `KeepRatio` is `true` (the default), then `Height` will continue to function as it currently does (performing a uniform scale to reach the specified height)

If `KeepRatio` is `false`, then `Height` will scale the model on the Z-axis only.

### `NodeConfiguration`
Add convenience methods to access the scale (Per recommendation from https://github.com/usnistgov/NetSimulyzer-ns3-module/issues/28#issuecomment-948262187):
`SetScale(double)`, `SetScale(Vector3D)`,  `SetScaleAxes(Vector3D)`, `GetScale()`, & `GetScaleAxes()`

**Comment by igs3000** [comment]
Hello Evan,

What I mentioned [previously](https://github.com/usnistgov/NetSimulyzer-ns3-module/issues/27#issuecomment-948224943) is only an abstract suggestion. Even, we can directly pass a 3D vector value or pass three separate double values and construct the necessary vector inside the function which is handling this - It doesn't matter.

Just like "SetPossition" method, we can set the scale.
` decoration->SetScale({0.0,0.0,0.0});`
For that imply, we have to change the double as Vector3DValue. 



Of course, it may be  'drop in' replacement.

But if we do scaling with one attribute, then we will not need anything further and avoid confusion with the new attribute "KeepAspectRatio" along with Height, Depth and Width. 

I am telling this from a “End User” perspective. But as a developer, you  may be having your own views on this issue(problems like 'drop in' replacement)

Charles Pandian

**Comment by bpe2** [comment]
This is in both the application and the module for a while now. Closing
