### ISSUE TITLE
Add CMake Support

### ISSUE THREAD

**Issue by bpe2** [usnistgov/NetSimulyzer-ns3-module#31]
ns-3 is planning on migrating from waf to CMake for ns-3.36. Add support for the new build system.

See: https://mailman.isi.edu/pipermail/ns-developers/2022-January/015606.html

**Comment by Gabrielcarvfer** [comment]
Hi, here is the patch for CMake :)

[netsimulyzer_cmake.txt](https://github.com/usnistgov/NetSimulyzer-ns3-module/files/7964494/netsimulyzer_cmake.txt)

**Comment by bpe2** [comment]
Wow, thanks @Gabrielcarvfer! If the CMake API is stable now, I'll get this is ASAP

**Comment by Gabrielcarvfer** [comment]
I hope it is, because I don't want to change these never again xD

**Comment by bpe2** [comment]
Well, aside from some awkwardness involving the `HAS_NETSIMULYZER` compile definition on modules added in `src/`. This looks good to go

**Comment by bpe2** [comment]
With the addition of the CMake variable instead of using the module list, I'm going to go ahead and close this
